version: '3'
services:
  web:
    build: docker-env/phpapache
    container_name: sf4_php7.2-apache
    environment:
      - VIRTUAL_HOST=my-project.lan
    ports:
      - "7100:80"
      - "7101:443"
    depends_on:
      - db
    volumes:
      - ./my-project:/var/www/html
      - ./docker-env/phpapache/vhost:/etc/apache2/sites-enabled/
      - ./docker-env/logs:/var/log
  db:
    image: mysql:5
    container_name: sf4_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    depends_on:
    - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
    - '8080:80'